# Generated by Django 2.1.3 on 2019-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField()),
                ('turn', models.IntegerField(default=0)),
                ('isPageVisited', models.BooleanField(default=False)),
            ],
        ),
    ]
