# Generated by Django 2.1.3 on 2019-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='pos1_2pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos1_3pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos1_4pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos2_2pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos2_3pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos2_4pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos3_3pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos3_4pmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pos4_4pmode',
            field=models.IntegerField(default=0),
        ),
    ]
