# Generated by Django 2.1.3 on 2019-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_auto_20190524_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
