# Generated by Django 2.1.3 on 2019-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_auto_20190524_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='diceNum',
            field=models.IntegerField(default=0),
        ),
    ]
